### ISSUE TITLE
Problem with tickets opened on external ticketers

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/temba-components#114]
These will have events without a user - i.e. `created_by` is null, e.g. a mailgun ticket that was reopened by a new email coming in. 

<img width="522" alt="Captura de Pantalla 2021-08-03 a la(s) 17 01 45" src="https://user-images.githubusercontent.com/675558/128092098-704becbc-36fc-44c4-ba46-c63883a2e6a3.png">

**Comment by ericnewcomer** [comment]
Fixed in https://github.com/nyaruka/temba-components/pull/125
