### ISSUE TITLE
Can we add check for custom Elements definition

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/temba-components#118]
Hi Team, we are using these components in our application Glific and sometimes when we don't refresh the page and load the library once again after removing with react-router it shows this Error:

`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry`

This happens because the page is not refreshed and we call the library once again after removing and it tries to register the custom elements again.

https://github.com/nyaruka/temba-components/blob/9d7e6757b0efc61c6f399bf97f817119ab5a909a/temba-modules.ts#L25

Can we add a check for this in the code: 
```
if (!window.customElements.get('temba-alert')) {
 window.customElements.define('temba-alert', Alert);  
 }
 ```
 
I know it won't affect anything in RapidPro since the page always gets refreshed on moving to a new flow that removes the custom Elements, but if you can add this check, that would be really helpful.

https://stackoverflow.com/a/58489650

Or If you guys have any other suggestions that would be super helpful.

**Comment by ericnewcomer** [comment]
Have you looked how this is handled in the flow editor (which like RapidPro has a sibling dependency on components).

https://github.com/nyaruka/floweditor/blob/main/src/index.js

**Comment by mdshamoon** [comment]
Hey Really sorry I was not clear on the issue. We are using floweditor package only and there we have these components. So If I move back to the floweditor screen from react-router then this error occurs, since the components have been registered by the floweditor and when we open it again it tries to re-register temba-components. 

It now fails since the page has not been refreshed and we call the floweditor package again with the same route after moving back.
