### ISSUE TITLE
Round times of upcoming events to nearest second

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/temba-components#175]
<img width="801" alt="Captura de Pantalla 2022-06-23 a la(s) 12 40 06" src="https://user-images.githubusercontent.com/675558/175291047-fcd9158e-89a6-4a52-b798-7856f6d70b82.png">

**Comment by rowanseymour** [comment]
Actually should probably just say `< 1 minute` since it doesn't fire with second-level accuracy

**Comment by ericnewcomer** [comment]
Whoops, that is supposed to round like the others. Good catch.

**Comment by ericnewcomer** [comment]
Right, I meant to the nearest minute.

**Comment by ericnewcomer** [comment]
This was fixed.
