### ISSUE TITLE
Select field does not truncate long words

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/temba-components#187]
**Issue**

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/32592458/182854726-180c394b-7f79-4fa6-b9d0-3a686cd460a7.png">

**Comment by mdshamoon** [comment]
@rowanseymour @ericnewcomer if you get some time can you please check on this?

**Comment by ericnewcomer** [comment]
I missed this one. Need to evaluate if this is still an issue. Definitely want to address that if so.

**Comment by ericnewcomer** [comment]
@mdshamoon do you still see this?

**Comment by mdshamoon** [comment]
Yes @ericnewcomer I have tested it today and the behaviour is the same

<img width="503" alt="image" src="https://user-images.githubusercontent.com/32592458/217977790-57f72588-2a67-4b00-89d6-ad7fe53cbc67.png">
