### ISSUE TITLE
create new compose component - form element with text, attachments, char counter, and send button

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/temba-components#249]
We'll want to add attachments to message broadcasts and contact chats. In order to do that, we need a self-contained component that lets you upload files and outputs a values list of urls.

It should:
  * Show upload progress
  * Show a list of previously uploaded files / types
  * Allow removal of previously uploaded files
  * Allow drag and drop on to a target to start an upload

**Comment by susanm74** [comment]
closing this based on the merging of https://github.com/nyaruka/temba-components/pull/256
