### ISSUE TITLE
compose - double focus on send button click

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/temba-components#274]
When acting on the send button directly, you can get a "double" focus appearance. Additionally, focus is not returned to the input. Ideally, in this case, the send button would lose focus immediately after the action is complete and the focus is returned to the input.

<img width="672" alt="Screenshot 2023-03-02 at 10 58 50 AM" src="https://user-images.githubusercontent.com/211652/222525978-7107d351-516a-4ebc-a97a-35d4e60e6020.png">

**Comment by susanm74** [comment]
@ericnewcomer sounds good, and then for cases where only the paperclip is displayed (and not the chatbox), will return focus to the paperclip

**Comment by susanm74** [comment]
@ericnewcomer

- i fixed the "return focus to chatbox after send" issue

- for the "double focus" issue, i think what is happening is that in the compose component, there's a ".container:focus-within" style, and then in the button component, there's a ".button-container:focus" style, and so when the send button is clicked, both of these are getting activated/applied... 
   - option 1 - is it possible to somehow exclude the inner button from triggering the outer compose ".container:focus-within" style?
   - option 2 - is it possible to modify the button component such that when the button is disabled, a click does not result in triggering the ".button-container:focus" style?

**Comment by ericnewcomer** [comment]
In the disabled state we should probably ignore pointer events. https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
