### ISSUE TITLE
broadcast crud interface - switch from text field to compose component

### ISSUE THREAD

**Issue by susanm74** [nyaruka/temba-components#282]
- current "create" scheduled message interface modal contains an area with a chatbox and char counter
- update that area to use the compose component containing chatbox, attachments, counter, no button
- needs to be updated in both old and new ui (with slight priority for new ui)
- don't worry about "send now" stuff yet
- rename "scheduled message" to "broadcast"

---
potentially relevant broadcast discussions:
- https://github.com/nyaruka/rapidpro/discussions/4219
- https://github.com/nyaruka/floweditor/discussions/1140
- https://github.com/nyaruka/floweditor/discussions/1120
- https://github.com/nyaruka/floweditor/discussions/1110

**Comment by susanm74** [comment]
<img width="627" alt="Screen Shot 2023-03-10 at 12 57 43 PM" src="https://user-images.githubusercontent.com/854012/224235538-2802d822-d825-4466-bb9f-bac1259459c6.png">

**Comment by susanm74** [comment]
![Uploading Screen Shot 2023-03-10 at 12.58.19 PM.png…]()

**Comment by susanm74** [comment]
@ericnewcomer qq - do we need to also update the "edit" interface modax (see above screenshot) to use the compose component? (and if yes, within the same, PR, follow-up PR? vs. no, don't worry about this yet)

**Comment by ericnewcomer** [comment]
Excellent point on updates

The update case should use the same modal as create (instead of the weird formax two-part thing). Since we are adding functionality to the create, we should either make the update work with it at the same time or in the next PR right after it. I'm fine with either.

**Comment by ericnewcomer** [comment]
Also, we should go ahead and rename these to Broadcasts now instead of scheduled messages.

**Comment by susanm74** [comment]
@ericnewcomer qq re: deleting broadcasts - if we get rid edit/read page and only display the create modax for create/edit/read, i think we lose the content menu containing the delete item and have to figure out where and how to re-add this - would it be the path of least resistance to simply add the compose component to the edit page, and then add the attachments list display to the read page? (and then re-work all of these create/edit/read UIs a bit more later?)
