### ISSUE TITLE
compose - set focus back on the chatbox - part deux

### ISSUE THREAD

**Issue by susanm74** [nyaruka/temba-components#292]
- whenever clicking the bottom "row" area containing the paperclip, counter, and send button... set the focus back on the chatbox
- immediately after selecting/uploading attachments...set the focus back on the chatbox

**Comment by ericnewcomer** [comment]
I noticed clicking near the edges was the same thing. Just make sure clicking anywhere inside the border (unless it's the send button or attachment button) focuses the textarea.
