### ISSUE TITLE
Render queued messages differently in contact histories

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/temba-components#384]
They could have a spinner, or be greyed... they ain't sent.

**Comment by ericnewcomer** [comment]
How do we feel about something like this?
<img width="250" alt="image" src="https://github.com/nyaruka/temba-components/assets/211652/a0c4c9c8-4bae-403d-a3ab-5bca866b52e2">

One issue here is the order is going to be creation order. Might make sense to have queued messages move to when they actually sent. But that sounds messy.

But once your queued messages send, your timeline is not a great representation of reality as it stands.

**Comment by ericnewcomer** [comment]
Also to answer a previous question about updating status in contact history, we only poll for events after a timestamp reflective of the most recent event. So, this means only the status of the most recent event could potentially be updated. I've reworked that so it updates now, but this won't matter when a message from way back when eventually sends. Of course, that only matters for the current page view. So maybe not that big of a deal. And as mentioned before, probably not in a meaningful order for the user to show it when it was queued over when it was sent. So perhaps some thinking to do there.
