### ISSUE TITLE
Can we make the main parser expressions configurable. 

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/temba-components#387]
https://github.com/nyaruka/temba-components/blob/b4a1579020dde01b7ccaf8dcd585e3f16fa8bc44/src/completion/helpers.ts#L24-L29

<img width="431" alt="image" src="https://github.com/nyaruka/temba-components/assets/32592458/7bb92fa6-0e17-4f97-a4b5-838c4c81e93b">

We want to include flow level details like name and id and uuid in our expressions. @flow.id, @flow.name etc. 
But these doesnt show up in auto completions since the first level has been hardcoded here. The rest is configurable with completions.json.

If possible can we made this configurable somehow with the help of completions.json.

**Comment by ericnewcomer** [comment]
Reopening. Open to taking a PR for this.
